### ISSUE TITLE
정보 출처는 어디인가요?

### ISSUE THREAD

**Issue by justiceHui** [sarojaba/awesome-devblog#151]
개발자 나정휘입니다.<br>
제 본명과 페이스북 프로필을 수집한 출처 부탁드립니다.

**Comment by justiceHui** [comment]
페이스북 프로필은 삭제 부탁드립니다.

추가로, 백준 온라인 저지(BOJ) jhnah917, 코드포스(Codeforces) Justice_Hui 프로필 추가해주시면 감사하겠습니다.<br>
https://www.acmicpc.net/user/jhnah917   <br>
https://codeforces.com/profile/Justice_Hui

누추한 블로그가 이런 곳에 등재되어 영광입니다.

**Comment by sarojaba** [comment]
db.yml 파일에 업데이트했습니다. 감사합니다.
