### ISSUE TITLE
어떻게 제 블로그가 추가되었는지... + 정보 추가

### ISSUE THREAD

**Issue by Shin-JaeHeon** [sarojaba/awesome-devblog#159]
안녕하세요. awesome-devblog으로 트래픽 유입이 들어와서 제 블로그가 이 곳에 추가된 것을 알았습니다. 이 곳에 추가되서 영광이라 생각하고 있습니다. 
제 블로그를 어떻게 아셨는지 알려주실 수 있나요?

추가로 정보를 추가할 수 있는지 궁금합니다.
npm : https://www.npmjs.com/~shin-jaeheon

**Comment by sarojaba** [comment]
안녕하세요. 웹 검색을 하다가 발견하거나, 생활코딩의 게시물을 보고 수집하고 있습니다.
아마도 생활코딩에 올리신 게시물을 보고 북마크해 놨는데, 최근에 정리하면서 등록한것 같네요.
https://www.facebook.com/groups/codingeverybody/permalink/2365032256870630/
NPM 주소 추가하였습니다. 감사합니다.

**Comment by Shin-JaeHeon** [comment]
감사합니다.
