### ISSUE TITLE
정보 수정 요청

### ISSUE THREAD

**Issue by adhrinae** [sarojaba/awesome-devblog#205]
안녕하세요 안도형입니다.
작년에 여기서도 정보 업데이트를 한 이후 `.dev` 도메인을 구입하여 블로그를 개편했는데
안내드리는 것을 잊고 있었네요.

블로그 주소를 `https://rinae.dev` 로 변경 부탁드리고 싶습니다.

**Comment by sarojaba** [comment]
이미 변경되었습니다. 제가 3월경에 변경된걸로 바꾼 이력이 있네요.
새로 등록한건 아니라서, 별개의 커밋으로 남기진 않았네요.
https://github.com/sarojaba/awesome-devblog/commit/91505605796b9e79afd45d6fdd357621750d38c9#diff-db62ffcced04f71944400ad9ae4310ce

**Comment by adhrinae** [comment]
미리 처리해주셔서 감사합니다. 그런데 README 파일에는 반영이 되어있지 않아서 문의를 드렸습니다.

**Comment by sarojaba** [comment]
아.. README의 목록은 더 이상 업데이트를 하지 않고 있습니다. 그리고 곧 삭제될 예정입니다.
https://github.com/sarojaba/awesome-devblog#국내-개인-사이트

**Comment by adhrinae** [comment]
제가 어제 목록을 볼 떄 상태가 상당히 안좋았나봅니다. 많은 것을 놓쳤네요 😢
