### ISSUE TITLE
검색을 한번하고, 같은 페이지상에서 새로운 키워드로 검색시 검색이 되지 않는 이슈

### ISSUE THREAD

**Issue by junwoochoi** [sarojaba/awesome-devblog#208]
![image](https://user-images.githubusercontent.com/26688947/62177023-6566d500-b37e-11e9-9119-4c89b9e4036d.png)

![image](https://user-images.githubusercontent.com/26688947/62177057-8deecf00-b37e-11e9-85ea-676e6945060f.png)

---

메인화면에서 '엘라스틱' 이라는 키워드로 검색을 한 번 실행한 뒤, 
현재 검색결과가 나와있는 화면에서 새로 다른 키워드로 검색시 url파라미터는 변경되지만 실제 검색은 작동하지 않습니다.

**Comment by sarojaba** [comment]
이슈 제보 감사합니다.
테스트가 부족했네요.
왜 안되는지 찾아보니 Nuxt 에 대해 아직 모르는 부분이 있었네요.
https://github.com/nuxt/nuxt.js/issues/2519
검색 기능 고쳤습니다. 해결되었다면 Close 부탁드립니다.

**Comment by junwoochoi** [comment]
빠른 대응 감사드립니다!
서비스 잘쓰고 있어요:)
