### ISSUE TITLE
정보 수정 요청드립니다 :D

### ISSUE THREAD

**Issue by madplay** [sarojaba/awesome-devblog#209]
안녕하세요.
트래픽 유입이 확인되어서 찾아보니 이런 멋진 곳이 있었네요!

다름이 아니라 수집된 정보 중에서 수정하고 싶은 부분이 있는데요.
관련하여 이 이슈를 생성하고 Pull Request로 수정 요청드립니다.

한가지 더, https://awesome-devblog.netlify.com/domestic 에서
제 실명(김태완)으로 국내 피드를 검색해보았는데요.
링크는 정상 동작하나, 모든 게시글이 동명이인의 이미지로 표기되는 것 같습니다.

감사합니다 :D

**Comment by sarojaba** [comment]
프로필 사진 수정했습니다.
확인 후 Close 부탁드립니다.

**Comment by madplay** [comment]
확인 완료했습니다. 감사합니다 :D
