### ISSUE TITLE
개인 목록, 개인 피드에서 보이지 않는 문제입니다.

### ISSUE THREAD

**Issue by yahwang** [sarojaba/awesome-devblog#217]
안녕하세요 yahwang.github.io 블로그 운영중인 황태식입니다. 
db.yml에 등록이 되어 있는데 개인 목록에서 확인이 안 되고
개인 피드에는 저번 달까지만 등록되고 이번 달 글은 등록이 되지 않는데 무엇이 잘못된 걸까요?

확인부탁드립니다.

**Comment by sarojaba** [comment]
안녕하세요.
최근에 JDK11로 올렸는데, 새로운 HttpClient로 교체한것이 문제가 되었네요.
소켓이 누수가나서 이름의 사전순으로 뒤쪽에 있으신 분들의 블로그는 수집이 안되었네요.
https://stackoverflow.com/questions/55271192/connections-leaking-with-state-close-wait-with-httpclient
수정했습니다. 알려주셔서 감사합니다.
