### ISSUE TITLE
feed 클릭 시 새탭에서 열리게 해주세요.

### ISSUE THREAD

**Issue by ppaarrkk** [sarojaba/awesome-devblog#227]
출근하면 항상 먼저 들어가는 사이트입니다. 잘 이용하고 있습니다.
feed 리스트에서 글 읽고 뒤로가면 항상 1페이지로 이동합니다.
새 창으로 띄어주시면 안될까요?

**Comment by sarojaba** [comment]
잘 이용하고 계신다니 저도 감사합니다.
혹시 좀 더 자세히 알려주실 수 있으신가요? 어떤 메뉴의 어떤 기능인지...
링크는 모두 새 탭으로 열리도록 적용되어 있는데, 누락된 부분이 있는건지 해서요.

**Comment by ppaarrkk** [comment]
https://awesome-devblog.now.sh/korean/people/feeds 에서 글을 읽을 때 새창으로 띄어주셨으면 좋겠습니다.

**Comment by sarojaba** [comment]
링크를 새창으로 띄우도록 개선하였습니다.
참고로, 해당 사이트는 UX 개선을 목표로, 재작성하고 있는 중으로, 아직 기본 기능만 개발되었습니다. 베타 버전으로, 모든 기능이 올바르지 않을 수 있습니다. 특별한 사유가 없다면, 현재 공식 사이트인 https://awesome-devblog.netlify.com 를 이용 부탁드립니다. (물론 https://awesome-devblog.now.sh 를 계속 사용하셔도 됩니다.)
