### ISSUE TITLE
수집 기준에 대해 궁금한점이 있어 질문드립니다.

### ISSUE THREAD

**Issue by goodGid** [sarojaba/awesome-devblog#230]
서비스 이용을 아주 잘하고 있는 유저입니다
늘 감사합니다 ㅎㅎ 

질문이 있는데
오늘(=23일) 기준으로
어제(=22일) 작성한 글에 대해서 
크롤링하여 23일에 메일로 전송을 해주시는데 

22일에 작성한 모든글을 
모두 크롤링하여 전송해주는건가요?
아니면 특정 기준으로 22일에 게시된 글 중 
적합한 글만 23일에 전송되는건가요? ㅎㅎ

**Comment by sarojaba** [comment]
안녕하세요. 메일 서비스에 관련된 문의는 아래의 채널을 통해 문의바랍니다.
https://gitter.im/daily-devblog/community
