### ISSUE TITLE
안녕하세요. 문의가 있어 이슈 남겨드립니다

### ISSUE THREAD

**Issue by lsjsj92** [sarojaba/awesome-devblog#244]
안녕하세요.
lsjsj92.tistory.com 블로그를 운영하고 있는 이수진이라고 합니다.

먼저 좋은 서비스 만들어주셔서 감사드립니다.

다름이 아니라 문의가 있어 이슈 남겨드립니다.
어썸데브블로그에 제 페이스북, 트위터 정보가 잘못되어 있습니다.

국내 -> 개인 목록에서 제 이름 이수진을 검색하면 제 블로그 계정에는 페이스북 정보가 없는데요.
http://devblog.selfhow.com/2019/08/19/%EA%BF%88-%EB%A7%8E%EC%9D%80-%EC%82%AC%EB%9E%8C%EC%9D%98-%EC%9D%B4%EC%95%BC%EA%B8%B0-python-%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%EC%97%90%EC%84%9C-grid-search%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98/

그러나 이쪽에서 넘어오는 경우에는 제 정보에 페이스북 정보가 보입니다.
해당 페이스북 정보는 저랑 동명이인이신 다른 '이수진'님으로 보입니다.

제 페이스북 계정은 lsjsj92@naver.com 입니다.
트위터는 없습니다.
가능하시다면 수정해주시면 감사하겠습니다 ㅠㅠ (이왕 등록된 것 제대로 등록되고 싶네요 ㅎㅎ)

다시 한 번 좋은 서비스 감사드립니다.

**Comment by sarojaba** [comment]
안녕하세요. 어썸데브블로그는 제가 운영하고 있지만, 말씀하신 서비스는 다른분이 이 레포의 목록을 이용해 서비스하고 있습니다. db.yml을 잘못 파싱하고 있는것 같네요. https://gitter.im/awesome-devblog/Lobby 들어오시면 selfhow 라는 분이 계신데, 그 분께 직접 말씀하셔야할것 같습니다. 감사합니다.
