### ISSUE TITLE
김남윤 블로그 이전해서 수정 해주시면 감사하겠습니다.

### ISSUE THREAD

**Issue by cheese10yun** [sarojaba/awesome-devblog#27]
제 이름 검색하니까 조회가 되네요...뭔가 감격스럽기도 하고 

그래도 블로그는 이전해서 수정 주셨으면 좋겠고 해서...

https://cheese10yun.github.io/

블로그 주소입니다.

**Comment by sarojaba** [comment]
변경했습니다. 이후 수정 사항있으면 직접 풀리퀘 날려주셔도 감사하겠습니다.
