### ISSUE TITLE
GitHub 로그인 에러

### ISSUE THREAD

**Issue by bum752** [sarojaba/awesome-devblog#279]
https://awesome-devblog.netlify.com/ 로그인시 `502 Bad Gateway`(`NO_STATUS_CODE_FROM_FUNCTION`) 에러가 발생합니다.

![image](https://user-images.githubusercontent.com/20104232/71564711-9e030a00-2ae8-11ea-84b1-ea05dbbcce89.png)

**Comment by sarojaba** [comment]
버그 제보해주셔서 감사합니다.
최초 로그인시에 초기 유저 정보를 생성하고 DB 에 저장하는 로직이 있습니다. 이 부분에서 해당 값이 변수에 설정이 안되는 케이스가 있었네요. DB에는 저장이 되었기 때문에, 처음 한번만 발생하고, 두번째 이후로는 발생 안했을것 같네요.
해당 이슈 보완했습니다. 확인 후 Close 부탁드립니다.

**Comment by bum752** [comment]
확인 감사합니다!
깃헙 로그인 페이지는 뜨지만 이후 과정에서 동일합니다.

**Comment by sarojaba** [comment]
제가 원인을 잘못 파악한것 같네요.
깃허브 인증 거치고, 웹사이트로 리다이렉트할때, 파라미터들을 URL로 보냅니다. 이 중에서 깃헙 프로필의 이름이 한글로 되어 있는 경우가 있어서, URL에 한글 전송이 안되었던것 같아요.
URL 인코딩하도록 보완했습니다. 확인 부탁드립니다.

**Comment by bum752** [comment]
우와! 해결되었습니다.
신경써주셔서 감사합니다~

이슈는 클로즈하도록 하겠습니다!
