### ISSUE TITLE
카카오톡 오픈 채팅 커뮤니티는 db 작성 안하시나요?

### ISSUE THREAD

**Issue by Sihan-Son** [sarojaba/awesome-devblog#314]
별도의 페이스북 페이지나 사이트없이 카카오톡 오픈 채팅으로만 운영되는 커뮤니티들은 수집 안하시는 궁금합니다

**Comment by sarojaba** [comment]
카카오톡 오픈 채팅은 전혀 생각해보지 못했네요.
괜찮은 커뮤니티가 있다면 목록에 추가해주시면 감사하겠습니다.

**Comment by Sihan-Son** [comment]
어디에 추가하면 될까요? 커뮤니티파일에 추가하면 될까요?

**Comment by sarojaba** [comment]
네. db_community.yml 에 추가하시면 될 것 같습니다.
