### ISSUE TITLE
국내-뉴스의 페이지네이션이 작동하지 않습니다.

### ISSUE THREAD

**Issue by dhmin5693** [sarojaba/awesome-devblog#338]
https://awesome-devblog.netlify.app/news/

생성되지 않은 리스트에 forEach가 붙어서인 걸로 추정됩니다.

**Comment by sarojaba** [comment]
제보 감사합니다. 보완될때까지 https://awesome-devblog.now.sh/korean/news 를 이용하시면 될것 같습니다.

**Comment by sarojaba** [comment]
백엔드 API 변경했는데, netlify.app 사이트보다 now.sh 에 더 집중하고 있었던터라, 변경 사항을 한쪽만 반영했었네요. 보완했습니다.
