### ISSUE TITLE
개인블로그 추가 후 반영이 안된 듯 합니다.

### ISSUE THREAD

**Issue by kimchanjung** [sarojaba/awesome-devblog#346]
김찬정으로 개인 블로그 추가 pull request 올리고 merge 되었습니다.
https://awesome-devblog.now.sh/korean/people
"김찬정"으로 검색 해본결과 검색되지 않는 것으로 보아 아직 반영이 안된 듯 한데
확인 부탁드립니다^^;;

**Comment by sarojaba** [comment]
현재 자동으로 웹에 반영되는 기능을 비활성화해놨습니다. 최대한 빠르게 해드리겠습니다.

**Comment by sarojaba** [comment]
등록되었습니다.

**Comment by kimchanjung** [comment]
반영 확인 하였습니다 감사합니다^^
