### ISSUE TITLE
블로그 포스트 리스트에 표시되는 프로필 이미지 설정 질문

### ISSUE THREAD

**Issue by kimchanjung** [sarojaba/awesome-devblog#353]
블로그 글 항목 리스트에 프로필 이미지가 표시되도록 하려면
어떻게 추가 하는지 궁금합니다.
db.yml
profile 항목인 것 같기도 하고  다른 사람들 설정을 보니 people/개인아이디.md
이렇게 되어 있던데 어떻게 설정하는지 잘 모르겠네요
아니면 페이스북 항목을 추가하면 자동으로 프로필 이미지가 표시되는 건지요?

**Comment by sarojaba** [comment]
1. people 디렉토리에 있는건 이제 사용되지 않고 있어요. (삭제 예정입니다.)
2. 기본적으로 RSS 내에 <rss><channel><image><url></url></image></channel></rss> 에 있는 이미지를 표시하고 있습니다. ex) https://medium.com/feed/@sarojaba
RSS에 해당 필드를 추가하시면 됩니다.
3. 하지만 만약 블로그 플랫폼에서 이미지를 넣어주지 않는 경우가 많아서, 추가적으로 github 계정이 함께 등록이 되어 있으면 github 프로필의 이미지를 표시해주는 기능이 있습니다. 하지만 현재는 제가 수동으로 연동시키고 있습니다. (모든 사람의 github 프로필을 Sync 하는 기능은 있지만, 목록에 사람이 많다보니, Github API Limit에 걸려서, 부득이하게 수동으로 바꿨습니다. 신규 등록된 사람만 Sync하는 기능은 개발 예정입니다.)

**Comment by sarojaba** [comment]
깃허브 프로필 등록했습니다. 새로 수집되는 블로그 포스트부터 프로필 이미지가 표시될거예요.

**Comment by kimchanjung** [comment]
처리 감사 드립니다 ^^
