### ISSUE TITLE
내용이 길어서 줄여진 (...) 항목은 마우스 커서를 올렸을 때 전체 내용을 보여 주면 어떨까요?

### ISSUE THREAD

**Issue by dontdieych** [sarojaba/awesome-devblog#371]
https://awesome-devblog.netlify.app/ 구독자 겸 애독자가 되려고 합니다. 만들어 주셔서 감사하구요. 건의 사항이 하나 있습니다.

![Screenshot_20200724_072407](https://user-images.githubusercontent.com/6509673/88344984-e08b7d00-cd7f-11ea-8799-66da87cb3b53.png)

요런 기능은 어떨런지요.

**Comment by sarojaba** [comment]
좋은 의견 감사합니다.
곧 업데이트할 수 있을 것 같습니다.

**Comment by sarojaba** [comment]
업데이트 했습니다.
