### ISSUE TITLE
티스토리 블로그 글의 경우 메일 피드에서 블로그 이미지가 노출되지 않음

### ISSUE THREAD

**Issue by bgc8214** [sarojaba/awesome-devblog#384]
기존에는 정상적으로 블로그의 대표 이미지가 노출이 되었는데, 얼마전부터 티스토리만 노출이 되지 않는 현상이
발생 중입니다.
티스토리 관련 부분이 변경된 것인지 확인이 필요합니다.

**Comment by sarojaba** [comment]
제보 감사합니다. 확인해보니 티스토리의 RSS에 대표 이미지가 사라졌네요. 버그인지, 앞으로 지원하지 않는지 모르겠습니다.

**Comment by sarojaba** [comment]
일단 자체 문제는 아니기 때문에 닫겠습니다.
