### ISSUE TITLE
fix: 검색창 에러 

### ISSUE THREAD

**Issue by Livenow14** [sarojaba/awesome-devblog#428]
![image](https://user-images.githubusercontent.com/48986787/102159890-c76aa080-3ec7-11eb-84e5-6f64bf73c177.png)

현재 메인화면에서 검색시 404에러가 발생합니다.
 다른 화면에서도 전체 검색시 404에러가 발생하는 것을 확인했습니다.

**Comment by sarojaba** [comment]
현상 확인 했습니다. 알려주셔서 감사합니다.

**Comment by sarojaba** [comment]
수정했습니다.
