### ISSUE TITLE
정보가 올바르게 등록이 되지 않은 것 같습니다.

### ISSUE THREAD

**Issue by dev-owen** [sarojaba/awesome-devblog#445]
안녕하세요.

블로그 db에 몇 달 전 제 정보를 업데이트 했었습니다.

https://github.com/sarojaba/awesome-devblog/pull/394/files

이후로 메일을 매번 확인하고 있는데 개발 관련 글들을 써도 리스트에 한 번도 없었던 것 같아서요.

한 번 확인 부탁드립니다.

감사합니다!

**Comment by sarojaba** [comment]
안녕하세요.

RSS 주소도 함께 등록해주셔야 자동 수집이 됩니다.
(글이 수집되는 것을 원하지 않는 분들도 계셔서, 부가적인 필드로 간주하고 있습니다.)
추가하시면 자동 수집될것 같습니다.

참고로, 매일 발신되는 메일 서비스(Daily DevBlog)과 관련된 문의는,
https://gitter.im/daily-devblog/community 에 문의하시면 될것 같습니다.
(목록에 관련된 문의는 저한테 하시면 됩니다.)

감사합니다.

2021년 1월 3일 (일) 오후 9:13, Wonjong Oh <notifications@github.com>님이 작성:

**Comment by dev-owen** [comment]
감사합니다 PR 등록했습니다.
