### ISSUE TITLE
db.yml 에 등록 하였으나, 개인목록에는 나오지 않습니다

### ISSUE THREAD

**Issue by thkwon1** [sarojaba/awesome-devblog#452]
안녕하세요 몇일 전에, `db.yml` 에 새로 블로그 정보 넣어서, [PR](https://github.com/sarojaba/awesome-devblog/pull/441) 올렸고, 반영된 것 까지 확인했는데,

개인 목록에서 이름 검색했을 때, 제 이름이 나오지 않아서 문의 드립니다

확인 가능 할까요?? 😄

**Comment by sarojaba** [comment]
웹페이지에는 자동으로 반영하지않고, 신규 명단을 모아서 정보들을 확인한 후에 반영하고 있습니다. 아마도 주말 이후에 확인하시면 반영되어있을것 같습니다.
