### ISSUE TITLE
새창열기 기능

### ISSUE THREAD

**Issue by kdh6429** [sarojaba/awesome-devblog#472]
컨텐츠를 보기 위해서 항상 해당 페이지에서 이동을해야하고
다시 목록으로 오기 위해서 다시 뒤로가기로 돌아와야합니다.
페이지 로드가 오래걸려 불편합니다. 
새창으로 열기를 지원하거나, 마우스 우클릭 > 새탭열기 기능이 동작할 수 있으면 좋겠습니다.

**Comment by sarojaba** [comment]
원래 내부 링크여서 Next.js의 Link 기능을 이용했는데, 웹 페이지와 REST API의 호스팅을 분리하면서 외부가 되어버려서 의미가 없어져버렸네요. 새탭으로 열기도 안되었고요.

**Comment by sarojaba** [comment]
보완했습니다. 확인 부탁드립니다.
