### ISSUE TITLE
개인 목록 페이지 목록 개수 설정이 가능하면 좋겠습니다.

### ISSUE THREAD

**Issue by dongwooklee96** [sarojaba/awesome-devblog#517]
![Screen Shot 2021-05-14 at 9 42 08 AM](https://user-images.githubusercontent.com/14002238/118204214-acad4f80-b498-11eb-9856-05eb529fb2ca.png)

안녕하세요, 어썸 데브 블로그에서 좋은 정보를 매일 읽는 개발자 입니다. 매우 좋은 서비스지만, 개인 목록 리스트가 너무 적고, 페이지를 넘길 때마다 이전 목록이 사라져서 불편한 점이 있습니다.

 - 따라서, 목록 개수를 지정하여 예) 10, 50, 100 불러올 목록을 설정할 수 있으면 좋겠습니다.

**Comment by sarojaba** [comment]
좋은 의견 감사드립니다!

**Comment by sarojaba** [comment]
목록 개수를 지정하는 기능을 추가했습니다.
https://awesome-devblog.netlify.app/korean/people

확인 부탁드립니다.

**Comment by dongwooklee96** [comment]
![Screen Shot 2021-05-31 at 7 50 42 AM](https://user-images.githubusercontent.com/14002238/120122626-eabea900-c1e4-11eb-93eb-e62026da3c47.png)

오 정말로 멋지네요! 감사합니다!

**Comment by dongwooklee96** [comment]
매일 아침 어썸데브 블로그를 확인하면서 시작하는게 일상이 되었습니다. 좋은 서비스를 만들어주셔서 감사합니다!

**Comment by sarojaba** [comment]
긍정적인 피드백 감사합니다!
