### ISSUE TITLE
블로그 글 수집이 안되는 것 같습니다.

### ISSUE THREAD

**Issue by kbs4674** [sarojaba/awesome-devblog#532]
안녕하세요, 최근 제 블로그 글 수집이 안되고 있어서 질문 드립니다.
`db.yml`에 이름, 블로그 주소, RSS 등록을 했음에도 불구하고 awesomedev에는 제 블로그 노출이 안되고 있는 것 같습니다.

노출안된 것 중에는 개발과 관련이 없는 뻘글도 있다보니 노출이 안돼도 상관없으나... 어제 날짜인 [6월 25일에 쓴 글](https://kbs4674.tistory.com/198) 만큼은 한번 어썸데브에 공유하고 싶습니다.
한번 확인 가능할까요?

감사합니다.

* 블로그 주소 : https://kbs4674.tistory.com/

**Comment by sarojaba** [comment]
안녕하세요. 확인해보니...
개발 관련이 아닌 글이 범람하는 것을 막기 위해, 블로그 포스팅의 카테고리로 수집을 제외하는 기능이 있습니다.
'나른한 하루' 라는 카테고리의 글은 개발 관련 글이 아니라고 판단하여 수집하지 않도록 막아놓았습니다.
6월 25일 작성하신 글도 '나른한 하루' 라는 카테고리에 속한 글이라서, 수집이 되지 않았습니다.

두가지 방안이 있을것 같습니다. 어떻게 생각하시나요?
1. 수집을 금지하는 카테고리를 해제하는 방안 (단, 향후 개발과 관련되지 않은 글이 계속 올라오지 않아야 합니다.)
2. 포스팅의 카테고리를 변경하여 올리는 방안 ('나른한 하루', '여행 일기' 를 제외한 카테고리로 옮기시면 될것 같네요.)

**Comment by kbs4674** [comment]
@sarojaba 답변 감사합니다. 혹시 1번 방안은 전체 글 수집에 대해, 2번 방안은 경우에는 [이번에 공유하고 싶은 포스팅 글](https://kbs4674.tistory.com/198)만 해당된다고 보면 될까요??

**Comment by sarojaba** [comment]
네. 맞습니다. 개발과 관련되지 않은 카테고리를 제외하고 수집됩니다.
카테고리를 옮기셨으니, 아마도 1~2일 사이에 수집될 것 같습니다.
하지만 아쉽게도, 최신글은 글 작성 시각순으로 표시되기 때문에, 첫페이지에 표시되지는 않을 것 같네요.

**Comment by kbs4674** [comment]
@sarojaba 알겠습니다! 처리해주셔서 감사합니다.
글 확인되면 해당 이슈는 close 하겠습니다.
