### ISSUE TITLE
도메인 변경 요청합니다.

### ISSUE THREAD

**Issue by devHudi** [sarojaba/awesome-devblog#55]
이슈를 남겨도 될진 모르겠지만, 저는 여기 등록된 L0GIC이라는 개발자입니다.

최근에 닉네임을 바꾸어 도메인도 http://blog.l0gic.me 에서 http://hudi.kr 로 변경되었는데 반영 해주실 수 있을까요?

**Comment by sarojaba** [comment]
최근에 좀 바빠서 처리가 늦었네요. 변경했습니다.
