### ISSUE TITLE
페이지 사이즈 15도 추가해주세요

### ISSUE THREAD

**Issue by ppaarrkk** [sarojaba/awesome-devblog#550]
FHD 에서 15개가 화면에 딱 들어맞네요..
사이즈 선택 콤보박스에는 15가 없어서 불편합니다.
![image](https://user-images.githubusercontent.com/13797188/127806371-ecefb369-1373-4eb5-9c9f-ea539c9437eb.png)

**Comment by sarojaba** [comment]
한 페이지에 표시되는 개수 15개 추가했습니다.
확인 부탁드립니다.
