### ISSUE TITLE
형재자매프로젝트 등록 가능할까요??@!

### ISSUE THREAD

**Issue by monkeyDugi** [sarojaba/awesome-devblog#555]
[사이트](http://devlogmoa.shop/)
[깃헙](https://github.com/monkeyDugi/dev_log_moa)

**Comment by sarojaba** [comment]
네. 당연하죠. 안그래도 제안드리려고 했는데...
조만간 업데이트 해놓겠습니다.

**Comment by monkeyDugi** [comment]
감사합니다~~
그런데 어떻게 아시고 제안하려고 하신거에요?
연락드린적이 없는데 궁금해서요!

**Comment by sarojaba** [comment]
며칠전에 생활코딩에 공유해주신 것 봤거든요 ^^
늦었지만 좋아요 꾸욱~

**Comment by monkeyDugi** [comment]
실례가 안된다면 기술적 질문 해도 될까요??
1. 미디엄 같은 경우 rss접근 시 403을 반환 하던데 어떻게 해결하셨나요? 저는 자바로 구현해서 Rome라이브러리를 사용 중이에요
2.  모든 rss형식이 같은건 아닌데 그런 부분은 케이스 별로 구현을 하셨나요? 아마 추상화를 잘 하셨을 것 같아서요
자바를 사용하셨다면 코드좀 볼 수 있을까여?

**Comment by sarojaba** [comment]
1. 저는 그런 경우를 겪어보지 못해서, 답변드리기 어려울 것 같아요. 아래 RSS도 403이 반환되나요?
https://medium.com/feed/@sarojaba
저도 Rome 라이브러리를 사용하고 있습니다.

2. Rome 자체가 충분히 추상화되어 있어서, 대부분의 케이스를 잘 처리하고 있습니다.
다만 말씀하신대로 Rome 라이브러리가 개발이 더이상 활발하지 않고, RSS 스펙을 준수하지 않는 피드들이 있어, 처리하지 못하는 피드들이 꽤 많이 있습니다. 하지만 저는 아직까지는 별도로 처리하려고 노력하지는 않고 있습니다. (그냥 버립니다.)
그러지 않더라도 충분히 수집 대상이 많고, 개인적으로 문의가 오면 그때마다 방안을 찾고 있습니다.
죄송하게도, 소스 코드는 여러 개인적인 이슈로 오픈하고 있지는 않습니다.

더 자세한 질문이나, 이 외에도 편하게 문의하시려면 [Gitter](https://gitter.im/awesome-devblog/Lobby) 이용해주셔도 좋을 것 같네요. ^^ (지금도 깃헙 이슈 제목과는 동떨어진 주제가 되어버려서요.)

**Comment by sarojaba** [comment]
등록했습니다.
