### ISSUE TITLE
Duplicated mege

### ISSUE THREAD

**Issue by jicjjang** [sarojaba/awesome-devblog#64]
#62, #63 PR에 대해서 #62 내용이 적용이 안됐습니다. Merge 과정에서 이슈가 있었던 것 같은데 확인 부탁드려요

**Comment by sarojaba** [comment]
수정하신 db.json 바뀌어 있는것 같은데요? 혹시 README 말씀하시는건가요?

**Comment by jicjjang** [comment]
헛... 제가 잘못봤군요 ㅠ 다시 PR드릴게요~
