### ISSUE TITLE
정보 업데이트 요청

### ISSUE THREAD

**Issue by adhrinae** [sarojaba/awesome-devblog#75]
안녕하세요. 안도형이라고 합니다.
먼저 이런 서비스를 구축하고 계셔서 존경스럽고 그 목록에 제 이름이 올라가 있어 영광입니다.

제가 두어달 전 대부분의 계졍 username을 교체하여 블로그 도메인 등도 전부 바뀌게 되어 반영 요청을 올리고자 합니다.

이전 블로그 주소: emaren84.github.io -> 현재 블로그 주소: adhrinae.github.io
RSS 주소는 앞부분을 제외하고는 동일
Twitter: adhrinae
Facebook: adh.rinae

번거로우시겠지만 나중에라도 변경해주시면 이 저장소를 찾고 서비스를 이용하는 분들께 조금이나마 도움이 되리라 생각합니다. 고맙습니다.

**Comment by sarojaba** [comment]
주소 변경했습니다.
감사합니다!
