### ISSUE TITLE
개인 블로그 추가 요청

### ISSUE THREAD

**Issue by bear2u** [sarojaba/awesome-devblog#83]
반갑습니다. 

개인적으로 운영하고 있는 블러그 추가 가능한지요?

블로그 주소: http://javaexpert.tistory.com
rss : http://javaexpert.tistory.com/rss
설명: 블록체인과 웹,모바일 관련 개인 공부 내용들 정리해서 올리고 있습니다.

**Comment by sarojaba** [comment]
네. 그런데 실명으로 등록하는것을 원칙으로 하고있습니다. 알려주시면 등록하겠습니다.

**Comment by sarojaba** [comment]
등록하였습니다.
